### PR TITLE
Add French CFG files (with fallback to original)

### PR DESCRIPTION
**Pull request by t0mg**
Ran my modified version of the script on the original CFG folder with French language and dates formatted as DD/MM/YYYY. This is the output (+ a couple of manual edits on MGS3 subsistence and Rez). Many English descriptions remain as the coverage seems lower in French language. I noticed a few outstanding misses for titles that are definitely in screenscarper.fr - maybe due to the search method ?

### CODE REVIEW

**Comment by Tom-Bruise** [comment]
This is great! So sorry I got to see this so late. 

I recently put together release 1.0, and I added a script to bump up the CfgVersion to 8 as seen in the latest OPL Manager. Would you mind rebasing to master (should be no conflicts) and upgrading your files from version 7 to 8 by running scripts/update_to_version.sh?

After integrating your changes I will put out release 1.1.

Thanks a lot again for your work!

**Comment by t0mg** [comment]
Sure, done! What difference does the version number make ? I'm new to OPL (and the PS2).

**Comment by Tom-Bruise** [comment]
I am new to the world of OPL as well. From what I understand from [this page](https://www.ps2-home.com/forum/viewtopic.php?f=111&t=5090), it denotes the file format version. They can probably check for the version number in certain (newer) versions of OPL to conditionally show/hide information and stuff like this. But I am not sure, I am just guessing. The latest OPL Manager offers the option to upgrade existing CFGs to version 8, and my interest was to make this database easy to use and future-proof.

**Comment by t0mg** [comment]
Thanks. I wish I could visit your link but apparently I'm a spam, I'm getting a 403 🙃

**Pull request merged**
